spring:
  application:
    name: bank1app
  ##################### DB #####################
  datasource:
    proxydatasource:
      url: jdbc:mysql://localhost:3306/bank1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT user()
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      connection-properties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
#  cloud:
#    alibaba:
#      seata:
#        tx-service-group: bank1app-fescar-service-group
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: root
#    jdbcUrl: jdbc:mysql://127.0.0.1:3306/bank1?useAffectedRows=true&serverTimezone=UTC&characterEncoding=utf-8
#    username: root


  main:
    allow-bean-definition-overriding: true



  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8





    
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true，注册中心的才为false
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群版
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #单机版
      defaultZone: http://localhost:8001/eureka/
  instance:
    instance-id: payment8002  #主机名的修改
    prefer-ip-address: true #访问路径可以显示ip
    #Eureka客户端向服务端发送心跳的实际间隔，单位为秒（默认为30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端收到最后一次心跳后等待时间上线，单位为秒（默认为90秒） 超时将剔除服务
    lease-expiration-duration-in-seconds: 2

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env
seata:
  tx-service-group: bank1app-fescar-service-group
  service:
    vgroup-mapping:
      bank1app-fescar-service-group: seata-server # 此处配置对应Server端配置registry.eureka.application的值
  registry:
    type: eureka
    eureka:
      service-url: http://127.0.0.1:8001/eureka/
      weight: 1

#feign:
#  hystrix:
#    enabled: true
#  compression:
#    request:
#      enabled: true # 配置请求GZIP压缩
#      mime-types: ["text/xml","application/xml","application/json"] # 配置压缩支持的MIME TYPE
#      min-request-size: 2048 # 配置压缩数据大小的下限
#    response:
#      enabled: true # 配置响应GZIP压缩
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 1000  # 设置熔断超时时间  default 1000
#        timeout:
#          enabled: true # 打开超时熔断功能 default true
#

ribbon:
  ConnectTimeout: 600 # 设置连接超时时间 default 2000
  ReadTimeout: 6000    # 设置读取超时时间  default 5000
  OkToRetryOnAllOperations: true # 对所有操作请求都进行重试  default false
  MaxAutoRetriesNextServer: 2    # 切换实例的重试次数  default 1
  MaxAutoRetries: 1     # 对当前实例的重试次数 default 0

#----------------------------seata----------------------------
#seata:
#  enabled: true
#  application-id: seata_server
#  tx-service-group: bank1app
#  enable-auto-data-source-proxy: true
#  use-jdk-proxy: false
#  service:
#    vgroup-mapping:
#      default: seata_server
#    enable-degrade: false
#    disable-global-transaction: false
#  registry:
#    type: eureka
#    eureka:
#      weight: 1
#      service-url: http://localhost:8001/eureka/
server:
  port: 8002
#----------------------------seata----------------------------